--- 
title: "Visualizing Colonization"
author: "Tabitha Sugumar & Madeleine Georges"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The broad topic of this project is colonization. However, we recognized early on that the nature of this subject meant it requires extensive historical work to contextualize data visualizations. Although we lacked deep historical knowledge on the subject, we hoped to use data to explore the potential impact of colonization, and potentially find trends, relationships, and/or indications that could be interesting to examine historically.

The questions that intrigued us included:
- What is the relationship between colonization and the current economic/social health of a country?
- What can we discover about the economic impact of colonialism overtime?
- What patterns can we find regarding the way in which countries' experienced colonialism (level of economic transformation, violence of independence, etc.)? 

Answering these questions proved to be very challenging. Particularly difficult obstacles to analysis included dealing with vasts amounts of missing data, and concern regarding the accuracy of data in the time period we were interested in. As a result we were hesitant to make any claims based on what our visualization. Despite this, even as we deliver this project we recognize that there is much more to be gleaned from this dataset. For example, it's possible to go in depth into a single relationship between a colonizing country and one of its colonies -- what we do here is a broader analysis that could potentially be a starting point for which relationships could be interesting to look at more closely. This is where we became very aware of the importance of domain knowledge for data scientists. Although we are not in any way historians, we found thinking about the challenges of working with historical data fascinating, and feel that this project is an interesting forray into applying data visualization techniques within the social sciences/humanities.
